### ISSUE TITLE
Avoid removing mesh parts

### ISSUE THREAD

**Issue by Megidd** [MarcoAttene/MeshFix-V2.1#10]
My original STL mesh looks like this:

![image](https://user-images.githubusercontent.com/17475482/104555354-f99c2900-5652-11eb-8790-7ee0a7923c48.png)

After fixing with MeshFix my mesh looks like this:

![image](https://user-images.githubusercontent.com/17475482/104555429-18022480-5653-11eb-97ff-0b8713b2a7e4.png)

Is there a way to avoid removing mesh parts? I intend to keep the original geometry.

Thanks

**Comment by Megidd** [comment]
Currently I'm using MeshFix on command line like this:

```batch
MeshFix.exe input.stl output_fixed.stl -a -j
```

**Comment by MarcoAttene** [comment]
MeshFix assumes that the input is a raw digitized model made of a single connected component (see the paper for details).
Apparently your STL file is not such a kind of model. That's why you observe this behaviour.
