### ISSUE TITLE
Build configuration

### ISSUE THREAD

**Issue by Megidd** [MarcoAttene/MeshFix-V2.1#11]
Usually, there are Visual Studio *release* and *debug* build configurations. But, there is only one VS build configuration named *Fast*:

![image](https://user-images.githubusercontent.com/17475482/104560833-b85c4700-565b-11eb-9d3c-4689e8a5f393.png)

Should the *Fast* configuration be used for both debugging and deployment/release?

Thanks.

**Comment by MarcoAttene** [comment]
If you need standard Debug/Release configs, you may use the CMakeLists provided (you need to install CMake for that).
> cd MeshFix-V2.1-master
> mkdir build
> cd build
> cmake ..

This will create a Visual Studio solution.
