### ISSUE TITLE
about mesh sharpening

### ISSUE THREAD

**Issue by nashdingsheng** [MarcoAttene/MeshFix-V2.1#12]
Hi, i want to consult whether this project or other project contain the c++ implementation of paper <<Edge-Sharpener:Recovering sharp features in triangulations of non-adaptively remeshed surfaces>> published by you in 2003. i want to do some work on mesh sharpening, but it do not know how to start. thank you

**Comment by MarcoAttene** [comment]
Hi,
Unfortunately that code is not included in meshfix. It is very old stuff
and I have no longer track of it. Nonetheless it should be rather
straightforward to reimplement it based on the paper.
Best wishes
Marco

Il mer 5 gen 2022, 11:21 nashdingsheng ***@***.***> ha
scritto:

**Comment by nashdingsheng** [comment]
ok, thank you, i will try to reimplement it myself
