### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by kennethassogba** [MarcoAttene/MeshFix-V2.1#9]
Hello,
I have install the program on my Debian 10 computer with the help on the CMakeList.
When I try to repair any .stl file (regardless of the file or of the option), I have a good output in the terminal but the output file is always empty.

Do you have a solution to this problem ?

Command:
`./MeshFix ../../1.STL`

Terminal result:
```
INFO- Loaded 6 vertices and 2 faces.
WARNING- Patching holes

0% done 2
100% done 
WARNING- Fixing degeneracies and intersections...
INFO- ********* ITERATION 0 *********
INFO- Removing degeneracies...
INFO- Removing self-intersections...

0 % done   
INFO- 4 intersecting triangles have been selected.

0 % done   
INFO- No intersections detected.
INFO- Saving output mesh ...
Elapsed time: 859 ms
```
Output file
```
OFF
# File created by MeshFix v2.0 (2016)

0 0 0
```

**Comment by MarcoAttene** [comment]
In some cases this might happen. MeshFix assumes that the input is a raw digitized model (see paper for details). You input does not appear to be such a kind of file, as it is made of just two triangles.
